version: "3.8"

services:
  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Rathod@9586
      MYSQL_DATABASE: hotel_app
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: backend
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: mysql_db
    ports:
      - "8090:8090"

  frontend:
    build: ./frontend
    container_name: front-container
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  mysql_data:
